[package]
name = "advent"
version = "0.1.0"
authors = ["Micxjo Funkcio <micxjo@fastmail.com>"]
license = "MIT"

[dependencies]
libc = "0.2.2"
regex = "0.1.43"
serde_json = "0.6.0"

[profile.test]
opt-level = 3